# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user_profile', '0004_auto_20180130_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flat',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер квартири'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house',
            field=models.PositiveIntegerField(default=0, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_symbol',
            field=models.CharField(blank=True, max_length=2, verbose_name='Символ будинку'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Жіноча', 'female'), ('Чоловіча', 'male')], max_length=10, verbose_name='Стать'),
        ),
    ]
